server:
  port: 3001

jwt-config:
  expiresIn: 604800

database:
  type: "mysql"
  isLogEnable: true
  synchronizeFlag: false
  encrypt: true
  trustServerCertificate: false
  name: "demo"

sawtooth:
  KEY_NAME: "transfer-chain.keys"
  API_URL: "http://rest-api:8008"
  KEY_ALGORITHMN: "secp256k1"
  TP:
    TRANSFER-CHAIN:
      FAMILY: "transfer-chain"
      VERSION: "0.0"
    CROSS-CHAIN:
      FAMILY2: "cross-chain"
      VERSION2: "0.1"
    PRODUCT:
      FAMILY: "product"
      VERSION: "0.1"